dist: bionic
language: cpp
compiler:
  - gcc
  - clang
install:
  - sudo apt update -y
  - sudo apt install -y ninja-build
script:
  - bash scripts/install-googletest.sh
  - ctest --build-and-test . build --build-generator Ninja --test-command ctest -V
